# Source: jxboot-helmfile-resources/templates/maven-settings-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"jenkins-maven-settings","properties":[{"name":"settingsXml","question":"Maven
      settings XML contents","help":"This is the maven settings XML which is mounted
      for Java builds","defaultValue":"\u003csettings\u003e\n    \u003c!-- sets the
      local maven repository outside of the ~/.m2 folder for easier mounting of secrets
      and repo --\u003e\n    \u003clocalRepository\u003e${user.home}/.mvnrepository\u003c/localRepository\u003e\n    \u003c!--
      lets disable the download progress indicator that fills up logs --\u003e\n    \u003cinteractiveMode\u003efalse\u003c/interactiveMode\u003e\n    \u003cmirrors\u003e\n        \u003cmirror\u003e\n        \u003cid\u003enexus\u003c/id\u003e\n        \u003cmirrorOf\u003eexternal:*\u003c/mirrorOf\u003e\n        \u003curl\u003ehttp://nexus:8081/repository/maven-group/\u003c/url\u003e\n        \u003c/mirror\u003e\n    \u003c/mirrors\u003e\n    \u003cservers\u003e\n        \u003cserver\u003e\n        \u003cid\u003enexus\u003c/id\u003e\n        \u003cusername\u003eadmin\u003c/username\u003e\n        \u003cpassword\u003eadmin123\u003c/password\u003e\n    \u003c/server\u003e\n    \u003cserver\u003e\n        \u003cid\u003eoss-sonatype-staging\u003c/id\u003e\n        \u003cusername\u003e\u003c/username\u003e\n        \u003cpassword\u003e\u003c/password\u003e\n        \u003c/server\u003e\n    \u003c/servers\u003e\n    \u003cprofiles\u003e\n        \u003cprofile\u003e\n            \u003cid\u003enexus\u003c/id\u003e\n            \u003cproperties\u003e\n                \u003caltDeploymentRepository\u003enexus::default::http://nexus/repository/maven-snapshots/\u003c/altDeploymentRepository\u003e\n                \u003caltReleaseDeploymentRepository\u003enexus::default::http://nexus/repository/maven-releases/\u003c/altReleaseDeploymentRepository\u003e\n                \u003caltSnapshotDeploymentRepository\u003enexus::default::http://nexus/repository/maven-snapshots/\u003c/altSnapshotDeploymentRepository\u003e\n            \u003c/properties\u003e\n        \u003c/profile\u003e\n        \u003cprofile\u003e\n            \u003cid\u003erelease\u003c/id\u003e\n            \u003cproperties\u003e\n                \u003cgpg.executable\u003egpg\u003c/gpg.executable\u003e\n                \u003cgpg.passphrase\u003emysecretpassphrase\u003c/gpg.passphrase\u003e\n            \u003c/properties\u003e\n        \u003c/profile\u003e\n    \u003c/profiles\u003e\n    \u003cactiveProfiles\u003e\n        \u003c!--make
      the profile active all the time --\u003e\n        \u003cactiveProfile\u003enexus\u003c/activeProfile\u003e\n    \u003c/activeProfiles\u003e\n\u003c/settings\u003e"},{"name":"securityXml","question":"Maven
      security XML contents","help":"This is the maven security XML which is mounted
      for Java builds","defaultValue":"\u003c\u003csettingsSecurity/\u003e"}],"mandatory":true}'
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: jx-labs-infra
  data:
  - name: settings.xml
    key: tf-jx-growing-ant-jx-maven-settings
    property: settingsXml
    version: latest
  - name: settings-security.xml
    key: tf-jx-growing-ant-jx-maven-settings
    property: securityXml
    version: latest
  template:
    type: Opaque
